# Generated by Django 5.2.7 on 2025-11-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        help_text="Descrição do endereço ou nome da parada",
                        max_length=255,
                    ),
                ),
                (
                    "latitude_longitude",
                    models.CharField(
                        help_text="Coordenadas no formato 'latitude,longitude' (ex: -24.7988039,-49.9928598)",
                        max_length=50,
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se a parada está atualmente em uso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parada",
                "verbose_name_plural": "Paradas",
                "ordering": ["endereco"],
            },
        ),
        migrations.CreateModel(
            name="Rota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome ou identificador da rota", max_length=200
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, help_text="Indica se a rota esta na operação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rota",
                "verbose_name_plural": "Rotas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="RotaParadaHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horario",
                    models.TimeField(
                        help_text="Horário programado para a passagem do ônibus nesta parada"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se este horário específico nesta parada/rota está ativo",
                    ),
                ),
                (
                    "parada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_rota",
                        to="rota.parada",
                    ),
                ),
                (
                    "rota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_parada",
                        to="rota.rota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário da Rota na Parada",
                "verbose_name_plural": "Horários das Rotas nas Paradas",
                "ordering": ["rota", "horario"],
                "unique_together": {("rota", "parada", "horario")},
            },
        ),
    ]
